apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
        - name: results
          image: docker.io/library/results-service:latest
          ports:
            - containerPort: 3000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: results-ingress
spec:
  rules:
    - http:
        paths:
          - path: /results
            pathType: Prefix
            backend:
              service:
                name: results-service
                port:
                  number: 3000